# How snakebitten is Nebraska's offense?

```{r}
library(tidyverse)
library(ggrepel)
```

```{r}
scoringoffense <- read_csv("~/Dropbox/SPMC350-Data-Literacy-and-Analytics-in-Sports/Data/ScoringOffense.csv")
totaloffense <- read_csv("~/Dropbox/SPMC350-Data-Literacy-and-Analytics-in-Sports/Data/TotalOffense.csv")
```

```{r}
offense <- left_join(totaloffense, scoringoffense, by=c('Year', 'Name'))
```

```{r}
nu <- offense %>% filter(Name == "Nebraska") %>% filter(Year == 2018)
```

```{r}
ggplot(offense, aes(x=`Yards/G`, y=`Points/G`)) + geom_point(color="grey") + geom_smooth(method=lm, se=FALSE) + labs(x="Total yards per game", y="Points per game", title="Snakebitten: Nebraska's offense", subtitle="The Husker's should be scoring way more than they are", caption="Source: NCAA | By Matt Waite") + theme_minimal() + theme(plot.title = element_text(size = 16, face = "bold"), axis.title = element_text(size = 8), plot.subtitle = element_text(size=10), panel.grid.minor = element_blank()) + geom_point(data=nu, aes(x=`Yards/G`, y=`Points/G`), color="red") + geom_text_repel(data=nu, aes(x=`Yards/G`, y=`Points/G`, label=Name)) 
```

```{r}
cor.test(offense$`Yards/G`, offense$`Points/G`)
```

```{r}
offenselm <- lm(offense$`Points/G` ~ offense$`Yards/G`)
summary(offenselm)
```

```{r}
head(nu)
```

```{r}
(432.2 * 0.101767) - 11.951726
```

